### ISSUE TITLE
general warning about ambiguous error message "CUST CONTACT THEIR BANK"

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#13]
This is something that has been a big but deceptively simple problem for our project. We would get these "CUST CONTACT THEIR BANK" errors reported by customers at times and couldn't work out what it means, and all st george could tell us was that it was a problem at the customers bank and not their problem....

Well it turns out they just reused that error message and it actually gives little guide as to that it, in this case was just incorrect CVV security code errors !!! as you will get the same text message for code 1, 2 and 5. yet 5 really should have its own message....
api docs:
05
CUST CONTACT
THEIR BANK
Failed security check, eg. CVN (Card Verification Number) on
back of card was entered incorrectly. Refer the customer to
their bank.

so if you want to get out the error code number from this library, use:
$ex->getResponseCode()

**Comment by mitchdav** [comment]
Thanks Hayden.
