### ISSUE TITLE
Notes on getting to work with PHP 7 / 8

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#14]
So some of the lib versions required by this package is not compatible with php 7 or 8

the current requirements are 
```
    "inacho/php-credit-card-validator": "^1.0",
    "sabre/xml": "^1.5",
    "guzzlehttp/guzzle": "^6.3"
```
sabre needs 3.0
guzzle im not sure, but my cms already had 7.4.5
inacho has not been updated so you have to manually edit the files, or try a fork

so:
composer require "guzzlehttp/guzzle:7.4.5 as 6.3"
composer require "sabre/xml:3.0 as 1.5"
composer require "mitchdav/st-george-ipg"

then i manually update inacho lib like so:
https://github.com/inacho/php-credit-card-validator/pull/28/files

**Comment by hayden-t** [comment]
to use a fork for inacho instead such as: https://github.com/jeebon/php-credit-card-validator/tree/master
add this to composer.json
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jeebon/php-credit-card-validator.git"
        }
    ]
```
than 

` composer require "inacho/php-credit-card-validator:dev-master as 1.0.2"`

before running 

`composer require "mitchdav/st-george-ipg"`

**Comment by mitchdav** [comment]
Hi Hayden,

I haven't worked with St. George IPG in many years now, so I am closing off this and any other issues, and archiving this repository now as it is not supported.

Please maintain your own fork if you are still using the project.

Thanks.

Mitch
