### ISSUE TITLE
What have you tried to work out what is going on with the ssl error you get now ?

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#2]
??

**Comment by mitchdav** [comment]
Hi Hayden,

Which provider are you using? And which SSL errors are you getting specifically?

If this is for the Webpay extension provider, have you tried using the WebService provider instead?  It will be significantly easier to setup and test on newer PHP versions.

Please provide as much information as possible so I can help you.

Thanks.

**Comment by hayden-t** [comment]
"UNABLE TO INITIALISE SSL" is the error,what is the webservice provider ? i use the one that you have to compile. arent i having the same error problem you have, when you say if you recompile it post july it doesnt work ?

**Comment by mitchdav** [comment]
You are using the Webpay extension provider, which I would strongly advise against.

Please have a look at the WebService documentation: https://github.com/mitchdav/st-george-ipg#webservice

It just uses a standard HTTP client to communicate with IPG, and won't require any compiling.

I wasn't able to resolve the SSL issues with the extension so our business just made the switch to the WebService provider instead.

If you have any trouble with the WebService provider please let me know.

**Comment by hayden-t** [comment]
ok, sounds like the best thing to do, so why would anyone use the extension option ? or is it just that there wasnt always an alternative ?
With the error itself for some poking around, i dont think it necessarily is a problem with ssl (though it could be) i started disabling code in webpay.c and recompiling and i wold still get the same error even though it was not even getting to the connection code. ie i think it just means "unable to initialise connection" not anything specific to ssl.

**Comment by mitchdav** [comment]
As far as I know St.George doesn't advertise their WebService offering, and instead just advertise the PHP (and other languages) SDK. I had to inquire as to whether they had a web-based option which fortunately they did. This package offers both for any users that wish to use one over the other, however given I can no longer get the extension to compile, I can't offer support for it any further.

Thanks for using this package!

**Comment by hayden-t** [comment]
Well thanks for making those inquiries, do you see any advantage to using the extension version ?

**Comment by mitchdav** [comment]
None at all, in fact quite the opposite.

The WebService provider is significantly easier to use and more consistent as far as setup as it just uses HTTPS to connect, so the only prerequisite is having a valid cacert.pem installed to verify St.George's SSL certificate, and you're all set to go.

The extension provider relies on a PHP version that is now [out of support](http://php.net/supported-versions.php) by PHP, so it really shouldn't be used any further.

**Comment by hayden-t** [comment]
I figured, well thanks for pointing all this out and making this library, maybe you could make this point bolder and more obvious at the top of your page as i skimmed past it all to get to the compile instructions as i already had an implementation and wasnt looking to use your library, but will now.
