### ISSUE TITLE
Unclear error message "Fatal error: Uncaught exception 'StGeorgeIPG\Exceptions\TransactionFailedException' with message 'Transaction failed after 0 tries.' "

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#5]
Looking at your code in Client.php, if it does all 3 max tries it starts at 3 and counts its way down b4 giving up but the error reported after the 3rd try and max tries has been depleted to 0 is indicating it has made 0 tries rather than 3 ...

**Comment by mitchdav** [comment]
Hi Hayden,

The max tries is modified here: https://github.com/mitchdav/st-george-ipg/blob/master/src/Client.php#L350

If you are seeing another exception that isn't being caught and reset by the above code, please let me know or submit a PR so it can be patched up.

Thanks.
