### ISSUE TITLE
your example or code creating uncaught exceptions

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#6]
So following your example with code here https://github.com/mitchdav/st-george-ipg/issues/3 its never getting to the "} catch (Exception $ex) {" bit and reporting details on the transaction and error, im just getting a fatal exception in php eg, 

> Fatal error: Uncaught exception 'InvalidArgumentException' with message 'The card expiry date is invalid.' in /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Request.php:289 Stack trace: #0 /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Request.php(740): StGeorgeIPG\Request::validateInputIsCardExpiryDate(1, 2000) #1 /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Client.php(164): StGeorgeIPG\Request->setCardExpiryDate(1, 2000) #2 /home/user/public_html/_webpay/_new/test.php(26): StGeorgeIPG\Client->purchase(1, 'ccnumber...', 1, 2000) #3 {main} thrown in /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Request.php on line 289

**Comment by hayden-t** [comment]
Ive been trying to work this out but am pretty stumped, are you expecting us to write our own error handlers ? I thought this library would be ready to use ?

**Comment by hayden-t** [comment]
I sought external help, and the problem seems that i was not putting the ->purchase in a try as well that had \Exception

**Comment by mitchdav** [comment]
Hi Hayden,

The example code provided is just that, an example, so if you are looking to use it in production I would advise taking standard precautions such as validating your input, or testing and monitoring it extensively. The exception tells you the error, which in this case relates to the card expiry date being invalid (in the past).

The example code just provides an example for how to get the library to work, and you can then integrate it into your application, and modify the code accordingly.

Thanks.

**Comment by hayden-t** [comment]
But it does not work as it throws fatal exceptions that stop the code execution. You need to make you example code $client->purchase section be in a try catch too to avoid this.

**Comment by mitchdav** [comment]
It only throws that exception if you don't use the code directly above it, which sets the expiration date of the test card to exactly 1 year in the future, in which case there won't be any validation errors for the expiration date being in the past.
