### ISSUE TITLE
Unexpected success on incorrect CVC 

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#7]
So if i put in empty cvc '' or 1 or 0 or anything less than 100 or even a string, it still completes transaction, not sure if this is problem with webservice or this library but just wanted to bring it up.
To get around this just did test,
` $cvc = (intval($cvc) > 99 ? intval($cvc) : 9999);//generate failure if invalid input`

**Comment by mitchdav** [comment]
Hi Hayden,

From my experience, the CVC code isn't validated against the actual card details by the IPG, so this is expected behaviour. The library can't do anything about it to validate it if it isn't validated by IPG, so I'll close this off as not an issue.

Thanks.

**Comment by hayden-t** [comment]
Incorrect, it is checked against their records and will fail if incorrect, but the submitted value has to be a integer over 99, otherwise it will seemingly dismiss it as if not submitted and approve the transaction regardless. As such you should  mention this behavior in your readme and put in a validator similar to what i suggested, as this is an important security feature that users may not realise is 'by-passable' in such ways.
